<?php

use App\Database\Migration;
use App\Models\DeliveryTariff;

class AddDeliveryTariffsToTableDeliveryTariff extends Migration
{
    public function up()
    {
        $distances = [
            ["from_address_id" => "1", "to_address_id" => "1", "distance" => 0, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "2", "distance" => 5500, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "3", "distance" => 6000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "4", "distance" => 7000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "5", "distance" => 10000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "6", "distance" => 8500, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "7", "distance" => 7500, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "8", "distance" => 11000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "9", "distance" => 12000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "10", "distance" => 4500, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "11", "distance" => 12000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "12", "distance" => 9000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "13", "distance" => 7000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "14", "distance" => 15000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "15", "distance" => 7000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "16", "distance" => 8000, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "17", "distance" => 9500, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "18", "distance" => 11700, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "19", "distance" => 7500, "price" => 50],
            ["from_address_id" => "1", "to_address_id" => "20", "distance" => 8500, "price" => 50],
        
            ["from_address_id" => "2", "to_address_id" => "1", "distance" => 2345, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "2", "distance" => 0, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "3", "distance" => 6789, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "4", "distance" => 7890, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "5", "distance" => 3456, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "6", "distance" => 7890, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "7", "distance" => 4567, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "8", "distance" => 5678, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "9", "distance" => 6789, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "10", "distance" => 1234, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "11", "distance" => 8901, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "12", "distance" => 4567, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "13", "distance" => 6789, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "14", "distance" => 8901, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "15", "distance" => 4567, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "16", "distance" => 6789, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "17", "distance" => 3456, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "18", "distance" => 9000, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "19", "distance" => 12000, "price" => 50],
            ["from_address_id" => "2", "to_address_id" => "20", "distance" => 7000, "price" => 50],
        
            ["from_address_id" => "3", "to_address_id" => "1", "distance" => 2345, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "2", "distance" => 550, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "3", "distance" => 0, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "4", "distance" => 7890, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "5", "distance" => 3456, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "6", "distance" => 7890, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "7", "distance" => 4567, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "8", "distance" => 5678, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "9", "distance" => 6789, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "10", "distance" => 1234, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "11", "distance" => 8901, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "12", "distance" => 4567, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "13", "distance" => 6789, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "14", "distance" => 8901, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "15", "distance" => 4567, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "16", "distance" => 6789, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "17", "distance" => 3456, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "18", "distance" => 9000, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "19", "distance" => 12000, "price" => 50],
            ["from_address_id" => "3", "to_address_id" => "20", "distance" => 7000, "price" => 50],
        
            ["from_address_id" => "4", "to_address_id" => "1", "distance" => 2345, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "2", "distance" => 550, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "3", "distance" => 7890, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "4", "distance" => 0, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "5", "distance" => 3456, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "6", "distance" => 7890, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "7", "distance" => 4567, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "8", "distance" => 5678, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "9", "distance" => 6789, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "10", "distance" => 1234, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "11", "distance" => 8901, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "12", "distance" => 4567, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "13", "distance" => 6789, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "14", "distance" => 8901, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "15", "distance" => 4567, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "16", "distance" => 6789, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "17", "distance" => 3456, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "18", "distance" => 9000, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "19", "distance" => 12000, "price" => 50],
            ["from_address_id" => "4", "to_address_id" => "20", "distance" => 7000, "price" => 50],
        
            ["from_address_id" => "5", "to_address_id" => "1", "distance" => 2345, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "2", "distance" => 550, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "3", "distance" => 3456, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "4", "distance" => 6789, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "5", "distance" => 0, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "6", "distance" => 7890, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "7", "distance" => 4567, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "8", "distance" => 5678, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "9", "distance" => 6789, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "10", "distance" => 1234, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "11", "distance" => 8901, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "12", "distance" => 4567, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "13", "distance" => 6789, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "14", "distance" => 8901, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "15", "distance" => 4567, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "16", "distance" => 6789, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "17", "distance" => 3456, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "18", "distance" => 9000, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "19", "distance" => 12000, "price" => 50],
            ["from_address_id" => "5", "to_address_id" => "20", "distance" => 7000, "price" => 50],
        
            ["from_address_id" => "6", "to_address_id" => "1", "distance" => 2345, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "2", "distance" => 8901, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "3", "distance" => 6789, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "4", "distance" => 7890, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "5", "distance" => 3456, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "6", "distance" => 0, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "7", "distance" => 4567, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "8", "distance" => 5678, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "9", "distance" => 6789, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "10", "distance" => 1234, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "11", "distance" => 8901, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "12", "distance" => 4567, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "13", "distance" => 6789, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "14", "distance" => 8901, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "15", "distance" => 4567, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "16", "distance" => 6789, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "17", "distance" => 3456, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "18", "distance" => 9000, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "19", "distance" => 12000, "price" => 50],
            ["from_address_id" => "6", "to_address_id" => "20", "distance" => 7000, "price" => 50],
        ];

        DeliveryTariff::insert($distances);
    }

    public function down()
    {
        //TODO реализовать пока заглушка
    }
}
